// Generated by gencpp from file ilk_paket/toplamRequest.msg
// DO NOT EDIT!


#ifndef ILK_PAKET_MESSAGE_TOPLAMREQUEST_H
#define ILK_PAKET_MESSAGE_TOPLAMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ilk_paket
{
template <class ContainerAllocator>
struct toplamRequest_
{
  typedef toplamRequest_<ContainerAllocator> Type;

  toplamRequest_()
    : a(0)
    , b(0)  {
    }
  toplamRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int32_t _a_type;
  _a_type a;

   typedef int32_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::ilk_paket::toplamRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ilk_paket::toplamRequest_<ContainerAllocator> const> ConstPtr;

}; // struct toplamRequest_

typedef ::ilk_paket::toplamRequest_<std::allocator<void> > toplamRequest;

typedef boost::shared_ptr< ::ilk_paket::toplamRequest > toplamRequestPtr;
typedef boost::shared_ptr< ::ilk_paket::toplamRequest const> toplamRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ilk_paket::toplamRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ilk_paket::toplamRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ilk_paket::toplamRequest_<ContainerAllocator1> & lhs, const ::ilk_paket::toplamRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ilk_paket::toplamRequest_<ContainerAllocator1> & lhs, const ::ilk_paket::toplamRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ilk_paket

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ilk_paket::toplamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ilk_paket::toplamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ilk_paket::toplamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ilk_paket::toplamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ilk_paket::toplamRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ilk_paket::toplamRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ilk_paket::toplamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef8322123148e475e3e93a1f609b2f70";
  }

  static const char* value(const ::ilk_paket::toplamRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef8322123148e475ULL;
  static const uint64_t static_value2 = 0xe3e93a1f609b2f70ULL;
};

template<class ContainerAllocator>
struct DataType< ::ilk_paket::toplamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ilk_paket/toplamRequest";
  }

  static const char* value(const ::ilk_paket::toplamRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ilk_paket::toplamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 a\n"
"int32 b\n"
;
  }

  static const char* value(const ::ilk_paket::toplamRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ilk_paket::toplamRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct toplamRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ilk_paket::toplamRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ilk_paket::toplamRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int32_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int32_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ILK_PAKET_MESSAGE_TOPLAMREQUEST_H
